[openai]
api_key = "3mwegFI754E5D7kfoVTM6k3MPMBiMu9w1qNUYnLtyTIFck0kkknBJQQJ99AKAC5RqLJXJ3w3AAAAACOGqncS"
[huggingface]
api_token = "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"
[github]
token = "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"
